name: base-repo-check(da-pilot/sling)

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  base-repo-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check base repository
        uses: actions/github-script@v7
        with:
          script: |
            const allowedBaseRepos = ['da-pilot/sling']; // Add allowed base repos here
            const baseRepo = context.payload.repository.full_name;
            if (!allowedBaseRepos.includes(baseRepo)) {
              core.setFailed(`❌ This PR must target one of these base repositories: ${allowedBaseRepos.join(', ')}. Current: ${baseRepo}`);
            } else {
              console.log(`✅ Base repository is valid: ${baseRepo}`);
            }
